### ISSUE TITLE
GHC 9 Compatibility: TypeApplications with Ticked Constructor 

### ISSUE THREAD

**Issue by konn** [tweag/ormolu#680]
This is the same as the one reported to [fourmolu](/parsonsmatt/fourmolu/issues/57).

**Describe the bug**
Current  ormolu formats `TypeApplications` with ticked constructor with a whitespace inserted in-between.
This works fine with GHC <= 8.10, but as GHC 9.0 introduced [whitespace-sensitive parsing of operators](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0#whitespace-sensitive-and-), this behaviour causes GHC to error saying that "Variable not in scope: (@)".

**To Reproduce**
Apply ormolu to the following:

```hs
{-# LANGUAGE TypeApplications #-}
foo = bar @'True
```

Then we get:

```hs
{-# LANGUAGE TypeApplications #-}
foo = bar @ 'True
```

**Expected behavior**
Input must remain unchanged:
```hs
{-# LANGUAGE TypeApplications #-}
foo = bar @'True
```

**Environment**
 - OS name + version: online

**Comment by utdemir** [comment]
It seems like your example gives the correct output on ormolu version `0.1.4.0`. I can only reproduce the behaviour you mentioned on version `0.1.3.1`. The fix at https://github.com/tweag/ormolu/issues/668 seems relevant which is introduced at `0.1.4.0`.

Could you check if you are indeed using an older version and if so, if you can reproduce it with `0.1.4.0`?

**Comment by konn** [comment]
I confirmed that the behaviour changed as expected in 0.1.4.0. Sorry for lack of version confirmation, and thank you for swift reply!
