### ISSUE TITLE
fails to build with ghc-9.12.3

### ISSUE THREAD

**Issue by juhp** [tweag/ormolu#1187]
While trying to build HLS with ghc-9.12.3:
```
Building library for ormolu-0.8.0.2...
[ 1 of 56] Compiling GHC.DynFlags     ( src/GHC/DynFlags.hs, dist/build/GHC/DynFlags.o, dist/build/GHC/DynFlags.dyn_o )
src/GHC/DynFlags.hs:18:3: error: [GHC-95909]
    • Constructor ‘Settings’ does not have the required strict field(s):
        sUnitSettings :: UnitSettings
    • In the expression:
        Settings
          {sGhcNameVersion = GhcNameVersion
                               {ghcNameVersion_programName = "ghc",
                                ghcNameVersion_projectVersion = cProjectVersion},
           sFileSettings = FileSettings {},
           sTargetPlatform = Platform
                               {platformArchOS = ArchOS
                                                   {archOS_arch = ArchJavaScript,
                                                    archOS_OS = OSUnknown},
                                platformWordSize = PW8, platformUnregisterised = True,
                                platformByteOrder = LittleEndian,
                                platformHasGnuNonexecStack = False,
                                platformHasIdentDirective = False,
                                platformHasSubsectionsViaSymbols = False,
                                platformIsCrossCompiling = False,
                                platformLeadingUnderscore = False,
                                platformTablesNextToCode = False, platformHasLibm = False,
                                platform_constants = Nothing},
           sPlatformMisc = PlatformMisc {},
           sToolSettings = ToolSettings
                             {toolSettings_opt_P_fingerprint = fingerprint0,
                              toolSettings_pgm_F = ""}}
      In an equation for ‘fakeSettings’:
          fakeSettings
            = Settings
                {sGhcNameVersion = GhcNameVersion
                                     {ghcNameVersion_programName = "ghc",
                                      ghcNameVersion_projectVersion = cProjectVersion},
                 sFileSettings = FileSettings {},
                 sTargetPlatform = Platform
                                     {platformArchOS = ArchOS
                                                         {archOS_arch = ArchJavaScript,
                                                          archOS_OS = OSUnknown},
                                      platformWordSize = PW8, platformUnregisterised = True,
                                      platformByteOrder = LittleEndian,
                                      platformHasGnuNonexecStack = False,
                                      platformHasIdentDirective = False,
                                      platformHasSubsectionsViaSymbols = False,
                                      platformIsCrossCompiling = False,
                                      platformLeadingUnderscore = False,
                                      platformTablesNextToCode = False, platformHasLibm = False,
                                      platform_constants = Nothing},
                 sPlatformMisc = PlatformMisc {},
                 sToolSettings = ToolSettings
                                   {toolSettings_opt_P_fingerprint = fingerprint0,
                                    toolSettings_pgm_F = ""}}
   |
18 |   Settings
   |   ^^^^^^^^...
```

https://download.copr.fedorainfracloud.org/results/petersen/haskell-language-server/fedora-rawhide-x86_64/09963163-haskell-language-server-ghc9.12/builder-live.log.gz

**Comment by juhp** [comment]
(This also affects @fourmolu btw)

**Comment by juhp** [comment]
I will continue to disable ormolu (and fourmolu) for fedora HLS 2.14 (built with cabal-install).
Though they build fine in Stackage Nightly, so not quite sure what is different/going on.
