### ISSUE TITLE
Add missing CONTRIBUTING.md file

### ISSUE THREAD

**Issue by abiduzz420** [tweag/ormolu#55]
Hi,

I want to propose the idea of having `CONTRIBUTING.md` file so that developers (especially new Haskell developers) can get useful guide on how to build, run and test the project on their local machines.

#### Helpful pointers that could be added:
- Whether to use cabal or stack?
- If cabal, then do we use v1 commands or are `cabal new-*` commands recommended ?
- If stack, then what should be the value of resolver?
- How to run a particular test instead of all tests?
- How to debug, make changes and see the changes in action?

I understand some of these things are quite basic and to some extent repetitive but adding these pointers are one way of learning about Haskell projects for beginners. This can definitely bring more developers to trying out new projects and bring obscure bugs to project maintainers notice.

I am currently facing problems in trying to setup the project locally and hence I have raised this issue. I tried to build the project using `cabal new-build` which produced the following error:
```
$ cabal new-build
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: ormolu-0.0.1.0 (user goal)
[__1] trying: gitrev-1.3.1 (dependency of ormolu)
[__2] next goal: template-haskell (dependency of gitrev)
[__2] rejecting: template-haskell-2.11.1.0/installed-2.1... (conflict: ormolu
=> ghc-boot-th>=8.4.3, template-haskell =>
ghc-boot-th==8.0.2/installed-8.0...)
[__2] rejecting: template-haskell-2.14.0.0, template-haskell-2.13.0.0,
template-haskell-2.12.0.0, template-haskell-2.11.1.0,
template-haskell-2.11.0.0, template-haskell-2.10.0.0,
template-haskell-2.9.0.0, template-haskell-2.8.0.0, template-haskell-2.7.0.0,
template-haskell-2.6.0.0, template-haskell-2.5.0.0, template-haskell-2.4.0.1,
template-haskell-2.4.0.0, template-haskell-2.3.0.1, template-haskell-2.3.0.0,
template-haskell-2.2.0.0 (constraint from non-upgradeable package requires
installed instance)
[__2] fail (backjumping, conflict set: gitrev, ormolu, template-haskell)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: template-haskell, ormolu, gitrev
```
I tried to remove `~./ghc` and `~/.cabal` directories, guessing that it could be due to conflict in the dependencies and re-ran `cabal new-build` but it failed.

Later I created `stack.yaml` and included `resolver: lts-13.19` but ran into different errors this time. Here's the short snippet of error-log (complete log is in this [link](https://gist.github.com/abiduzz420/7f60529e381e7faf607aa4c4a84f4804)) :
```
$ stack build
Building all executables for `ormolu' once. After a successful build of all of them, only specified executables will be rebuilt.
ormolu-0.0.1.0: build (lib + exe)
Preprocessing library for ormolu-0.0.1.0..
Building library for ormolu-0.0.1.0..
[11 of 24] Compiling Ormolu.Printer.Meat.Type ( src/Ormolu/Printer/Meat/Type.hs, .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/Ormolu/Printer/Meat/Type.o )

/home/abiduzair/Documents/uzair/ormolu/src/Ormolu/Printer/Meat/Type.hs:36:3: error:
    Not in scope: data constructor ‘HsAppsTy’
    Perhaps you meant ‘HsAppTy’ (imported from GHC)
   |
36 |   HsAppsTy apps ->
   |   ^^^^^^^^

/home/abiduzair/Documents/uzair/ormolu/src/Ormolu/Printer/Meat/Type.hs:53:3: error:
    Not in scope: data constructor ‘HsPArrTy’
    Perhaps you meant ‘HsParTy’ (imported from GHC)
   |
53 |   HsPArrTy t -> located t (bracketsPar . p_hsType)
   |   ^^^^^^^^
...
...
...
--  While building package ormolu-0.0.1.0 using:
      /home/abiduzair/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build lib:ormolu exe:ormolu --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```
I would like to know what are your thoughts on adding `CONTRIBUTING.md` file and how I could resolve the project setup issues mentioned above. I am happy to raise a PR for the same, if I can successfully run the project locally. Thank you :)

**Comment by judah** [comment]
#33 mentions that ghc-8.6 isn't supported yet.  You'll either want to build using `cabal` with ghc-8.4 in your path, or else use `lts-12` instead of `lts-13`.

**Comment by mrkkrp** [comment]
I think it's a good idea. We have something in the readme right now, but it doesn't cover everything. With cabal, you need GHC 8.4.4 to be installed, alternatively use Nix, e.g.:

```
$ nix-shell -p haskell.compiler.ghc844
<inside shell>
$ cabal new-update
$ cabal new-build
```

With stack, something like this could work:

```
resolver: lts-12.26
packages:
- '.'
extra-deps:
- path-io-1.4.2
```

**Comment by mrkkrp** [comment]
I added the `CONTRIBUTING.md` file.
