### ISSUE TITLE
No instance for (Bounded Extension) arising from a use of ‘minBound’

### ISSUE THREAD

**Issue by ad-si** [tweag/ormolu#496]
Tried to build it on macOS with stack and got following error:

```txt
[39 of 41] Compiling Ormolu.Parser

/Users/adrian/Tests/ormolu/src/Ormolu/Parser.hs:194:16: error:
    • No instance for (Bounded Extension)
        arising from a use of ‘minBound’
    • In the expression: minBound
      In the expression: [minBound .. maxBound]
      In an equation for ‘allExts’: allExts = [minBound .. maxBound]
    |
194 |     allExts = [minBound .. maxBound]
    |                ^^^^^^^^
```

**Comment by neongreen** [comment]
Which GHC version and ghc-lib-parser version were used for the build?

**Comment by neongreen** [comment]
Perhaps we should go back to pinning the ghc-lib-parser version.

**Comment by ad-si** [comment]
I was using the stack lts-14.3 as described in your documentation, but with 14.20 and 13.19 it didn't work either…

**Comment by neongreen** [comment]
Yeah, the Bounded instance only appeared in 8.8.1 and lts-14.3 includes
8.8.0.

We would either have to add a more restrictive lower bound, or go via Enum
instead of Bounded if we want to keep using the ghc-lib-parser provided by
Stackage.

**Comment by neongreen** [comment]
@mrkkrp which one should it be? Do you care about sticking to Stackage versions or not?

**Comment by mrkkrp** [comment]
The lower bound seems to be correct in both master and the released version on Hackage:

```
ghc-lib-parser >= 8.8.1 && < 8.8.2
```

I do not understand how it could build with 8.8.0 given these bounds.

Here is what I use:

```
resolver: lts-14.03
packages:
- '.'

extra-deps:
- ghc-lib-parser-8.8.1@sha256:81dc4ed6ae6b7ccfda1e62e3c2d9a8600f8ecf45e4237d4dc099ccd4b74db180
```

**Comment by mrkkrp** [comment]
Closing, since currently we have correct lower bound, unless I'm missing something here.
